Bootstrap: oras
From: {{ORAS_REPO}}/ubuntu22.04_turbovnc:latest

%arguments
	ORAS_REPO=ghcr.io/uw-psych/hyakvnc_apptainer
	FREESURFER_DEB=freesurfer.deb
	FREESURFER_VERSION=7.4.1
	FREESURFER_HOME=/usr/local/freesurfer/{{FREESURFER_VERSION}}
	FREESURFER_DL_URL=https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/{{FREESURFER_VERSION}}/freesurfer_ubuntu22-{{FREESURFER_VERSION}}_amd64.deb

%help
	This is an Apptainer container of Ubuntu 22.04 with TurboVNC and FreeSurfer installed.

%files
	../scripts/install-freesurfer.sh /opt/install-freesurfer.sh
	freeview.desktop /usr/share/applications/freeview.desktop

%environment freesurfer
	export FREESURFER_HOME={{FREESURFER_HOME}}
	# Settings from SetupFreeSurfer.sh:
	export OS="Linux"
    export FS_OVERRIDE=0
    export FIX_VERTEX_AREA=""
    export FSF_OUTPUT_FORMAT="nii.gz"
	export SUBJECTS_DIR="$FREESURFER_HOME/subjects"
    export FUNCTIONALS_DIR="$FREESURFER_HOME/sessions"
    export MNI_DIR="$FREESURFER_HOME/mni"
    export LOCAL_DIR="$FREESURFER_HOME/local"
    export MINC_BIN_DIR="$FREESURFER_HOME/mni/bin"
    export MINC_LIB_DIR="$FREESURFER_HOME/mni/lib" 
    export MNI_DATAPATH="$FREESURFER_HOME/mni/data"
	export PERL5LIB="$MINC_LIB_DIR/perl5/5.8.5" \
    export MNI_PERL5LIB="$MINC_LIB_DIR/perl5/5.8.5" \
    export PATH="$FREESURFER_HOME/bin:$FREESURFER_HOME/tktools:$MINC_BIN_DIR:$PATH"
	export SHELL="/bin/bash"
	export LC_ALL='C.UTF-8'
	export LANG='C.UTF-8'

%post
	# Enable exit on error:
	set -e

	# Trace shell commands:
	set -x

	export FREESURFER_HOME="{{FREESURFER_HOME}}"
	export DEBIAN_FRONTEND=noninteractive
	export LC_ALL='C.UTF-8'
	export LANG='C.UTF-8'
	
	# Update apt:
	apt-get update --yes --quiet

	# Install freesurfer:
	/opt/install-freesurfer.sh && echo "Installed freesurfer" || exit 1

	# Remove freesurfer installer:
	rm -f /opt/install-freesurfer.sh

	# Clean up packages:
	apt-get clean --yes --quiet && rm -rf /var/lib/apt/lists/*
