
Bootstrap: localimage
From: {{CONTAINERDIR}}/ubuntu22.04_interactive.sif

%arguments
	CONTAINERDIR=../

%help
	This is an Apptainer container of Ubuntu 22.04 with TurboVNC installed.

%labels
	MAINTAINER "Altan Orhon - altan@uw.edu"

%environment
	export VNC_DEFAULT_PASSWORD="password"
	export PATH="/opt/TurboVNC/bin:$PATH"
	export TVNC_WM=xfce
	export HYAKVNC_USER_BASE_DIR="/vnc"
	export HYAKVNC_USER_SOCKET="${HYAKVNC_USER_BASE_DIR}/socket.uds"
	export HYAKVNC_USER_LOGFILE="${HYAKVNC_USER_BASE_DIR}/vnc.log"
	export HYAKVNC_USER_PASSWORDFILE="${HYAKVNC_USER_BASE_DIR}/passwd"
	export HYAKVNC_USER_DISPLAY=":1"

%post
	set -e
	export DEBIAN_FRONTEND=noninteractive
	apt-get update -qq
	
	# Install TurboVNC dependencies:
	apt-get install -y -q \
		libpam0g \
		libxt6 \
		libxext6 \
		xauth \
		x11-xkb-utils \
		xkb-data \
		libturbojpeg \
		python3

	# Install TurboVNC:
	wget https://sourceforge.net/projects/turbovnc/files/3.0.91%20%283.1%20beta2%29/turbovnc_3.0.91_amd64.deb && dpkg -i turbovnc_3.0.91_amd64.deb && rm turbovnc_3.0.91_amd64.deb && apt-get install --fix-broken -y -q

	apt-get install -y -qq --no-install-recommends \
		xfce4 \
		at-spi2-core \
		gnome-keyring \
		libpam-gnome-keyring \
		gnome-keyring-pkcs11 \
		gpg-agent \
		gnupg \
		libnotify-bin \
		xfce4-notifyd \
		xfce4-whiskermenu-plugin \
		thunar \
		xfce4-terminal \
		thunar-archive-plugin \
		xarchiver \
		thunar \
		thunar-volman \
		gvfs \
		policykit-1-gnome \
		gvfs-backends \
		tumbler \
		udisks2 \
		xdg-user-dirs \
		dbus \
		dbus-x11 \
		dbus-broker \
		python3-dbus \
		dbus-user-session

	# Clean up packages:
	apt-get clean -y -qq && rm -rf /var/lib/apt/lists/*
	echo '$vncUserDir = "$ENV{HYAKVNC_USER_BASE_DIR}";' >> /etc/turbovncserver.conf
	
%apprun vncpasswd
	# Set VNC password:
	VNC_PASSWORD="${1:-${VNC_PASSWORD:-${VNC_DEFAULT_PASSWORD:-}}}"
	VNC_PASSWORD_FILE="${2:-${VNC_PASSWORD_FILE:-${HYAKVNC_USER_PASSWORDFILE:-}}}"
	mkdir -p "$(dirname "${VNC_PASSWORD_FILE}")" \
		&& echo "${VNC_PASSWORD}" | vncpasswd -f > "${VNC_PASSWORD_FILE}" \
		&& chmod 600 "${VNC_PASSWORD_FILE}" \
		&& echo "Set VNC password to ${VNC_PASSWORD} in file ${VNC_PASSWORD_FILE}"

%apprun vncserver
	# Set password if not exists:
	mkdir -p "$(dirname "${HYAKVNC_USER_BASE_DIR}")"
	[ -e "${HYAKVNC_USER_PASSWORDFILE}" ] || /scif/apps/vncpasswd/scif/runscript
	echo "$(uname -n)" > "${HYAKVNC_USER_BASE_DIR}/hostname" \
	&& exec vncserver \
		"${HYAKVNC_USER_DISPLAY}" \
		-fg \
		-uds \
		-log "${HYAKVNC_USER_LOGFILE}" \
		-rfbunixpath "${HYAKVNC_USER_SOCKET}" \
		"${@}"

%apprun vnckill
	[ -e "${HYAKVNC_USER_SOCKET}" ] && vncserver -kill "${HYAKVNC_USER_DISPLAY}"

%runscript
	# Run app vncserver:
	exec /scif/apps/vncserver/scif/runscript

