
Bootstrap: {{BOOTSTRAP_SOURCE}}
From: {{BOOTSTRAP_REPO}}/ubuntu22.04_interactive:latest

%arguments
	BOOTSTRAP_SOURCE=oras
	BOOTSTRAP_REPO=ghcr.io/uw-psych/hyakvnc_apptainer

%files
	../_common/scripts/install-turbovnc.sh /opt/install-turbovnc.sh
	../_common/configs/sview.desktop /usr/share/applications/sview.desktop
	../_common/configs/xfce4 /configs-xfce4

%help
	This is an Apptainer container of Ubuntu 22.04 with TurboVNC and XFCE installed.

%environment
	export VNC_DEFAULT_PASSWORD="password"
	export PATH="/opt/TurboVNC/bin:$PATH"
	export TVNC_WM=xfce
	export HYAKVNC_USER_BASE_DIR="/vnc"
	export HYAKVNC_USER_SOCKET="${HYAKVNC_USER_BASE_DIR}/socket.uds"
	export HYAKVNC_USER_LOGFILE="${HYAKVNC_USER_BASE_DIR}/vnc.log"
	export HYAKVNC_USER_PASSWORDFILE="${HYAKVNC_USER_BASE_DIR}/passwd"
	export HYAKVNC_USER_DISPLAY=":10"

%post
	set -e # Exit on error
	set -x # Print commands as they are executed
	export DEBIAN_FRONTEND=noninteractive

	# Update package list:
	apt-get update --yes --quiet
	
	# Install TurboVNC:
	/opt/install-turbovnc.sh && echo "Installed TurboVNC" || exit 1
	rm -f /opt/install-turbovnc.sh

	# Install XFCE:
	apt-get install --yes --quiet \
		xfce4 \
		xfce4-goodies

	# Install additional packages:
	apt-get install --yes --quiet \
		dbus-x11 \
		dbus-broker \
		fonts-droid-fallback \
		fonts-liberation \
		fonts-noto-mono \
		fonts-opensymbol \
		fonts-powerline \
		sview \
		xclip \
		xdg-user-dirs \
		xdg-user-dirs-gtk \
		xdg-utils \
		xsel
	
	# Clean up packages:
	apt-get clean --yes --quiet && rm -rf /var/lib/apt/lists/*
	
	# Move XFCE configs to correct directories:
	mkdir -p /etc/xdg/xfce4/xfconf/xfce-perchannel-xml /etc/xdg/xfce4/whiskermenu /etc/xdg/xfce4/terminal
	mv /configs-xfce4/xfconf/xfce-perchannel-xml/*.xml /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/
	mv /configs-xfce4/whiskermenu/defaults.rc /etc/xdg/xfce4/whiskermenu/
	mv /configs-xfce4/terminal/terminalrc /etc/xdg/xfce4/terminal/
	rm -rf /configs-xfce4

	# Set xfce4-terminal as default terminal emulator:
	update-alternatives --set x-terminal-emulator /usr/bin/xfce4-terminal.wrapper

	# Set up TurboVNC's base directory to be in the container's /vnc directory:
	echo '$vncUserDir = "$ENV{HYAKVNC_USER_BASE_DIR}";' >> /etc/turbovncserver.conf

	
%apprun vncpasswd
	# Set VNC password:
	VNC_PASSWORD="${1:-${VNC_PASSWORD:-${VNC_DEFAULT_PASSWORD:-}}}"
	VNC_PASSWORD_FILE="${2:-${VNC_PASSWORD_FILE:-${HYAKVNC_USER_PASSWORDFILE:-}}}"
	mkdir -p "$(dirname "${VNC_PASSWORD_FILE}")" \
		&& echo "${VNC_PASSWORD}" | vncpasswd -f > "${VNC_PASSWORD_FILE}" \
		&& chmod 600 "${VNC_PASSWORD_FILE}" \
		&& echo "${APPTAINER_NAME:-}: Set VNC password to ${VNC_PASSWORD} in file ${VNC_PASSWORD_FILE}"

%apprun vncserver
	# Set password if not exists:
	mkdir -p "$(dirname "${HYAKVNC_USER_BASE_DIR}")"
	[ -e "${HYAKVNC_USER_PASSWORDFILE}" ] || /scif/apps/vncpasswd/scif/runscript
	echo "$(uname -n)" > "${HYAKVNC_USER_BASE_DIR}/hostname" \
	&& exec vncserver \
		"${HYAKVNC_USER_DISPLAY}" \
		-fg \
		-uds \
		-log "${HYAKVNC_USER_LOGFILE}" \
		-rfbunixpath "${HYAKVNC_USER_SOCKET}" \
		"${@}"

%apprun vnckill
	[ -e "${HYAKVNC_USER_SOCKET}" ] && vncserver -kill "${HYAKVNC_USER_DISPLAY}"

%runscript
	# Run app vncserver:
	exec /scif/apps/vncserver/scif/runscript

