Bootstrap: docker
From: ubuntu:22.04

%help
	This is an Apptainer container of Ubuntu 22.04 for interactive use.

%labels
	Maintainer altan@uw.edu
	Version v0.0.1

%environment
	export DEBIAN_FRONTEND=noninteractive
	export LC_ALL='C.UTF-8'
	export LANG='C.UTF8'
	export TZ='America/Los_Angeles'

%post
	export DEBIAN_FRONTEND=noninteractive
	export LC_ALL='C.UTF-8'
	export LANG='C.UTF8'
	export TZ='America/Los_Angeles'

	apt-get update -qq

	# Install basic tools:
	apt-get install -y -qq \
		make \
		nano \
		vim \
		bash-completion \
		curl \
		iproute2 \
		netcat-openbsd \
		less \
		git \
		net-tools
	
	# Install GitHub CLI:
	curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
	chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
	echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null

	apt-get update -qq && apt-get install -y -qq gh
	# Clean up packages:
	apt-get clean -y -qq && rm -rf /var/lib/apt/lists/*

%runscript
	exec "${@}"
