Bootstrap: docker
From: ubuntu:22.04

%help
	This is an Apptainer container of Ubuntu 22.04 for interactive use.

%labels
	Maintainer altan@uw.edu

%environment
	export LANG=C.UTF-8
	export LC_ALL=C.UTF-8
	export TZ=America/Los_Angeles

%post
	set -e # Exit on error
	set -o pipefail # Exit on pipe error
	set -x # Print commands as they are executed
	export DEBIAN_FRONTEND=noninteractive
	export TZ='America/Los_Angeles'
	export LANG=C.UTF-8
	export LC_ALL=C.UTF-8

	# Don't generate these locales:
	mkdir -p /var/lib/locales/supported.d
	for localename in fr de zh-hant ja es it zh-hans pt ru ar; do
		rm -f /var/lib/locales/supported.d/$localename && \
		touch /var/lib/locales/supported.d/$localename && \
		chmod a-r /var/lib/locales/supported.d/$localename
	done
	
	# We want man pages:
	echo Y | unminimize
	
	# Update package list:
	apt-get update -qq

	# Install basic tools:
	# apt-utils: for apt utilities
	# bash-completion: for bash completion of commands
	# curl: for downloading files
	# findutils: for find, xargs, etc. to find files
	# gawk: for awk to process text files
	# git: for git to manage source code
	# iproute2: for ip to manage network
	# less: for less to view files
	# locales: for localedef to install locales
	# make: for make to build things
	# man: for man pages
	# man-db: for man pages
	# nano: for nano to edit files
	# net-tools: for ifconfig, netstat, etc. to manage network
	# netcat-openbsd: for nc, etc. to work with network connections
	# openssh-client: for ssh and scp to connect to other machines
	# procps: for ps, top, etc. to manage processes
	# psmisc: for killall, etc. to manage processes
	# python3-full: for python3 to run scripts
	# vim: for vim to edit files
	# xz-utils: for xz to uncompress files
	# zip: for zip to compress files

	apt-get install --yes --quiet \
		apt-utils \
		bash-completion \
		bash-doc \
		bzip2 \
		curl \
		findutils \
		gawk \
		git \
		iproute2 \
		less \
		locales \
		make \
		man \
		man-db \
		nano \
		net-tools \
		netcat-openbsd \
		openssh-client \
		socat \
		procps \
		psmisc \
		python3-full \
		vim \
		xz-utils \
		zip

	# Install en_US.UTF-8 locale:
	localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

	# Install GitHub CLI:
	curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
	chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
	echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
	apt-get update --quiet && apt-get install --yes --quiet gh

	# Clean up packages:
	apt-get clean -y -qq && rm -rf /var/lib/apt/lists/*

