Bootstrap: localimage
From: ../ubuntu22.04_graphical/ubuntu22.04_graphical.sif

%help
	This is an Apptainer container of Ubuntu 22.04 with X and TigerVNC installed.

%labels
	MAINTAINER "Altan Orhon - altan@uw.edu"

%post
	export DEBIAN_FRONTEND=noninteractive
    export LC_ALL='C.UTF-8'

	apt-get update -qq
	
	apt-get install -y -qq --no-install-recommends \
		xfce4 \
		xfce4-terminal \
		fonts-liberation \
		xfce4-whiskermenu-plugin \
		xfce4-taskmanager \
		xfce4-indicator-plugin \
		xfce4-screenshooter \
		ristretto \
		mousepad \
		thunar-archive-plugin \
		thunar-volman \
		tumbler \
		tumbler-plugins-extra \
		xarchiver \
		ffmpegthumbnailer

	# Clean up packages:
	apt-get clean -qq -y && rm -rf /var/lib/apt/lists/*

	# Set XFCE as default:
	update-alternatives --set x-terminal-emulator /usr/bin/xfce4-terminal.wrapper
	update-alternatives --set x-session-manager /usr/bin/xfce4-session

