Bootstrap: localimage
From: ../ubuntu22.04_interactive/ubuntu22.04_interactive.sif

%help
	This is an Apptainer container of Ubuntu 22.04 with X and TigerVNC installed.

%labels
	MAINTAINER "Altan Orhon - altan@uw.edu"

%post
	export DEBIAN_FRONTEND=noninteractive
	export LC_ALL=C.UTF-8

	apt-get update -qq
	apt-get install -y -qq \
		xorg \
		xterm \
		xfonts-100dpi \
		xfonts-75dpi \
		x11-xfs-utils \
		tigervnc-standalone-server \
		tigervnc-common \
		tigervnc-xorg-extension \
		tigervnc-tools \
		dbus-x11

	# Clean up packages:
	apt-get clean -y && rm -rf /var/lib/apt/lists/*

	# Configure TigerVNC to work without password (preferable on SSH):
	echo '$SecurityTypes = "None";' >> /etc/tigervnc/vncserver-config-mandatory
	

%apprun vncserver
	exec vncserver "${@}"

%runscript
	exec vncserver "${@}"

%startscript
	exec vncserver "${@}"
