Bootstrap: localimage
From: {{CONTAINERDIR}}/ubuntu22.04_turbovnc.sif

%arguments
	CONTAINERDIR=../

%post
	set -e
	export DEBIAN_FRONTEND=noninteractive
	export LC_ALL='C.UTF-8'
	export LANG='C.UTF-8'

	apt-get update -qq
	
	apt-get install -y -q \
		xfce4 \
		xfce4-goodies \
		at-spi2-core \
		gnome-keyring \
		thunar \
		thunar-volman \
		thunar-archive-plugin \
		file-roller \
		xdg-user-dirs \
		xdg-user-dirs-gtk \
		xdg-utils \
		zip \
		bzip2 \
		libfuse2 \
		libnotify-bin \
		libpam-gnome-keyring \
		packagekit \
		policykit-desktop-privileges \
		evince \
		desktop-file-utils \
		gvfs \
		gvfs-backends \
		gvfs-fuse \
		xubunutu-core \
		fonts-liberation \
		fonts-opensymbol \
		fonts-powerline
	
	# Clean up packages:
	apt-get clean -y -qq && rm -rf /var/lib/apt/lists/*

