Bootstrap: localimage
From: ../ubuntu22.04_interactive/ubuntu22.04_interactive.sif

%help
	This is an Apptainer container of Ubuntu 22.04 with X and TigerVNC installed.

%labels
	MAINTAINER "Altan Orhon - altan@uw.edu"

%files
	./*.sh /usr/local/bin

%post
	export DEBIAN_FRONTEND=noninteractive
	export LC_ALL='C.UTF-8'
	export LANG='C.UTF-8'
	export VNCSERVER_DEFAULT_PASSWORD='password'
	apt-get update -qq

	apt-get install -y -q \
		xterm \
		tigervnc-standalone-server \
		tigervnc-common \
		tigervnc-xorg-extension \
		tigervnc-tools \
		novnc \
		dbus-x11 \
		xserver-xorg-input-all \
		xauth \
		xfonts-base \
		xkb-data \
		at-spi2-core

	apt-get install -y -q --no-install-recommends \
		xubuntu-core \
		fonts-liberation \
		fonts-opensymbol \
		fonts-ubuntu

	apt-get install -y -q \
		libfuse2 \
		libnotify-bin \
		xfce4-artwork \
		xfce4-indicator-plugin \
		xfce4-screenshooter \
		xfce4-statusnotifier-plugin \
		xfce4-terminal \
		xfce4-whiskermenu-plugin \
		xfce4-xkb-plugin \
		xfce4-panel-profiles \
		evince \
		thunar-archive-plugin \
		xarchiver \
		ristretto \
		mousepad \
		tumbler


	# Clean up packages:
	apt-get clean -y -qq && rm -rf /var/lib/apt/lists/*

	# Configure TigerVNC default password
	echo "$VNCSERVER_DEFAULT_PASSWORD" | vncpasswd -f > /etc/vncpasswd-insecure.conf
	echo '$SecurityTypes = "VncAuth";' >> /etc/tigervnc/vncserver-config-defaults
	echo '$vncPasswdFile = "/etc/vncpasswd-insecure.conf";' >> /etc/tigervnc/vncserver-config-defaults
	echo '$vncStartup = "/usr/local/bin/start-xubuntu.sh";' >> /etc/tigervnc/vncserver-config-defaults

%apprun vncserver
	vncserver -verbose -fg -PasswordFile /etc/vncpasswd-insecure.conf "${@}"

%runscript
	vncserver -verbose -fg -PasswordFile /etc/vncpasswd-insecure.conf "${@}"

%startscript
	vncserver -verbose -PasswordFile /etc/vncpasswd-insecure.conf "${@}"
