Bootstrap: localimage
From: ../ubuntu22.04_interactive/ubuntu22.04_interactive.sif

%help
	This is an Apptainer container of Ubuntu 22.04 with X and TigerVNC installed.

%labels
	MAINTAINER "Altan Orhon - altan@uw.edu"

%files
	./*.sh /usr/local/bin

%environment
	export VNC_DEFAULT_PASSWORD=password
	export TVNC_WM=xfce
	export PATH="/opt/TurboVNC/bin:$PATH"
%post
	set -e
	export DEBIAN_FRONTEND=noninteractive
	export LC_ALL='C.UTF-8'
	export LANG='C.UTF-8'
	apt-get update -qq
	
	# Install TurboVNC dependencies:
	apt-get install -y -q \
		libpam0g \
		libxt6 \
		libxext6 \
		xauth \
		x11-xkb-utils \
		xkb-data \
		python3 

	# Install TurboVNC:
	wget https://sourceforge.net/projects/turbovnc/files/3.0.91%20%283.1%20beta2%29/turbovnc_3.0.91_amd64.deb && dpkg -i turbovnc_3.0.91_amd64.deb && rm turbovnc_3.0.91_amd64.deb && apt-get install --fix-broken -y -q

	apt-get install -y -q \
		xfce4 \
		xfce4-goodies \
		at-spi2-core \
		gnome-keyring \
		thunar \
		thunar-volman \
		thunar-archive-plugin \
		file-roller \
		xdg-user-dirs \
		xdg-user-dirs-gtk \
		xdg-utils \
		zip \
		bzip2 \
		libfuse2 \
		libnotify-bin \
		libpam-gnome-keyring \
		packagekit \
		policykit-desktop-privileges \
		evince \
		desktop-file-utils \
		gvfs \
		gvfs-backends \
		gvfs-fuse \
		libturbojpeg

	apt-get install -y -q --no-install-recommends \
		xubuntu-core \
		fonts-liberation \
		fonts-opensymbol \
		fonts-ubuntu \
		fonts-powerline

	# Clean up packages:
	apt-get clean -y -qq && rm -rf /var/lib/apt/lists/*

%apprun vncpasswd
	# Set VNC password:
	echo "${1:-${VNC_DEFAULT_PASSWORD}}" | vncpasswd -f > "${2:-${HOME}/.vnc/passwd}" && chmod 600 "${2:-${HOME}/.vnc/passwd}" && echo "Set VNC password to ${1:-${VNC_DEFAULT_PASSWORD}}"

%apprun vncclean
	# Clean stale VNC sessions:
	echo "Cleaning stale VNC sessions..." /usr/local/bin/clean-stale-vnc.sh "${@}"

%apprun vncserver
	# Set password if none:
	[ -e "${HOME}/.vnc/passwd" ] || /scif/apps/vncpasswd/scif/runscript
	# Clean stale sessions:
	/scif/apps/vncclean/scif/runscript
	vncserver -fg "${@}"

%runscript
	# %apprun vncserver:
	exec /scif/apps/vncserver/scif/runscript "${@}"

%startscript
	# %apprun vncserver:
	exec /scif/apps/vncserver/scif/runscript "${@}"
