Bootstrap: localimage
From: {{CONTAINERDIR}}/ubuntu22.04_xubuntu.sif

%arguments
	CONTAINERDIR=../

%help
	This is an Apptainer container of Ubuntu 22.04 with FreeSurfer installed.

%labels
	MAINTAINER "Altan Orhon - altan@uw.edu"

%environment
	FREESURFER_VERSION='7.4.1'
	export FREESURFER_HOME="/usr/local/freesurfer/${FREESURFER_VERSION}"

%post
	export DEBIAN_FRONTEND=noninteractive
	export LC_ALL='C.UTF-8'
	export LANG='C.UTF-8'
	FREESURFER_VERSION='7.4.1'
	FREESURFER_DEB_URL=https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/${FREESURFER_VERSION}/freesurfer_ubuntu22-${FREESURFER_VERSION}_amd64.deb
	DLPATH=$(mktemp --suffix=.deb)
	export FREESURFER_HOME="/usr/local/freesurfer/${FREESURFER_VERSION}"

	# Install dependencies for freesurfer:
	apt-get update -y -q && apt-get upgrade -y -q && apt-get install -y -q --no-install-recommends minc-tools

	# Download freesurfer binary package and install:
	curl -L -o "${DLPATH}" "${FREESURFER_DEB_URL}" && dpkg -i "${DLPATH}" && rm "${DLPATH}"

	# Fix dependencies:
	apt-get --fix-broken install -y -q --no-install-recommends

	# Clean up packages:
	apt-get clean -y -qq && rm -rf /var/lib/apt/lists/*

	# Set up freesurfer environment:
	."${FREESURFER_HOME}/SetUpFreeSurfer.sh"
